### ISSUE TITLE
lines is not defined

### ISSUE THREAD

**Issue by LaisRast** [derhuerst/vbb-cli#12]
Hey,
Sometimes `vbb-journey` exits after selecting the journey, giving me the following error:
``lines is not defined``
![error](https://user-images.githubusercontent.com/29920417/50619240-514a1a80-0ef8-11e9-8b49-fd537a902a05.png)

**Comment by derhuerst** [comment]
Can you please give me the version of `vbb-cli` you're using? Run `vbb-journey -v`.

**Comment by derhuerst** [comment]
Nevermind, the issue is [here](https://github.com/derhuerst/vbb-cli/blob/27291fca5dd2457adb83c259f53dc754ef6a9b2f/lib/line-color.js#L8). Will fix.

**Comment by derhuerst** [comment]
Published as `vbb-cli@1.0.2`. Thanks!
