### ISSUE TITLE
Geo location not working

### ISSUE THREAD

**Issue by leifwenzel** [derhuerst/vbb-cli#13]
When calling vbb-dep with option -l i get the following error:
`vbb-dep -l
(node:61008) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/local/lib/node_modules/vbb-cli/node_modules/vbb-util/package.json' of './src/index'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
Geocoding service returned unexpected status code: 404`

**Comment by derhuerst** [comment]
Okay, the warning is actually unrelated to the geolocation logic. Does the geolocation feature work for you?

I have fixed the warning in derhuerst/vbb-util@6e4b612.

**Comment by leifwenzel** [comment]
Yes, today the geolocation feature is working again. Seems to be a temporary problem with the Geocoding service.
And the deprecation warning is also gone.
