### ISSUE TITLE
"Bad Gateway"

### ISSUE THREAD

**Issue by phlind** [derhuerst/vbb-cli#7]
Since today I have a problem when using vbb-dep or vbb-route. The selection of stations works, but instead of the result I just get "Bad Gateway".

**Comment by derhuerst** [comment]
This is because the VBB API, [which I wrap into an API](https://github.com/derhuerst/vbb-rest/blob/master/docs/index.md#berlin--brandenburg-public-transport-api), is down frequently. See [the status monitor](https://status.transport.rest). Stations search is done by my API directly.

**Comment by derhuerst** [comment]
What I can do is improve errors though, both in the API as well as in the CLI client.

**Comment by derhuerst** [comment]
Have to admit that in this specific case, it is my "fault", as the VBB migrated its API to use 9-digit station IDs. They didn't have a test server or a migration phase (in which both formats are accepted) though. 🙄

**Comment by derhuerst** [comment]
Should work again now.

**Comment by derhuerst** [comment]
FYI the upstream API by VBB [seems to be more reliable now](https://status.transport.rest). Don't know why.
