### ISSUE TITLE
products filter not working

### ISSUE THREAD

**Issue by aqueiros** [derhuerst/vbb-cli#8]
Greetings, first of all, great tool. 
I was trying it out, and it seems like the products filter is not working for me.
As an example, this was the output for 
_vbb-dep Oranienburger Str --products="tram"_
<img width="346" alt="screenshot 2017-09-29 16 17 54" src="https://user-images.githubusercontent.com/12710413/31019987-e15c5110-a531-11e7-8a4e-ec9a70ed83d1.png">
Looks like the SBahn is also coming out. I was not expecting that. Am I doing something wrong?

**Comment by derhuerst** [comment]
hey! thanks for using my tool.

as far as i remember, `vbb-dep` has no products filter (although it would be possible to build one). `vbb-route` does.

**Comment by aqueiros** [comment]
Well, in the examples it is being used in vbb-dep. And in anycase, it is also not working for vbb-route. So I would keep the issue open. But up to you.

**Comment by derhuerst** [comment]
You're right about both points.

**Comment by derhuerst** [comment]
`vbb-cli@0.6.1` fixes this.
